In [29]:
import pandas as pd
import numpy as np

In [69]:
list1 = pd.read_excel('./파워링크1.xlsx')
list1 = list1.drop(index=0)
list2 = pd.read_excel('./파워링크2.xlsx')
list2 = list2.drop(index=0)
list3 = pd.concat([list1, list2], axis=0)
list3 = list3.iloc[:,2:]
list3.reset_index(drop=True,inplace = True)

In [60]:
list3

,키워드,입찰가 유형,입찰가,품질지수,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
0,호두강정,키워드,1000.0,4.0,291,3,1.04,1093,3278
1,호두정과답례품,키워드,1000.0,5.0,669,2,0.30,671,1342
2,결혼답례품견과류,기본,70.0,4.0,0,0,0.00,0,0
3,결혼답례품호두강정,기본,70.0,4.0,0,0,0.00,0,0
4,결혼답례품호두정과,기본,70.0,4.0,0,0,0.00,0,0
5,결혼식답례품호두강정,기본,70.0,4.0,0,0,0.00,0,0
6,답례품호두강정,기본,70.0,4.0,1,0,0.00,0,0
7,답례품호두정과,기본,70.0,4.0,0,0,0.00,0,0
8,답례호두강정,기본,70.0,4.0,0,0,0.00,0,0
9,답례호두정과,기본,70.0,4.0,0,0,0.00,0,0
10,호두강정답례품,키워드,1000.0,4.0,207,0,0.00,0,0
11,호두강정선물세트,기본,70.0,4.0,1,0,0.00,0,0
12,호두답례품,기본,70.0,4.0,1,0,0.00,0,0
13,호두정과답례,기본,70.0,4.0,1,0,0.00,0,0
14,호두정과선물,기본,70.0,4.0,1,0,0.00,0,0
15,호두정과선물세트,기본,70.0,4.0,1,0,0.00,0,0
16,호두정과답례품,키워드,1000.0,5.0,4399,23,0.53,1052,24189
17,호두강정,키워드,1000.0,4.0,3740,16,0.43,996,15939
18,호두강정답례품,키워드,1000.0,4.0,489,2,0.41,770,1540
19,결혼답례품견과류,기본,70.0,4.0,0,0,0.00,0,0
20,결혼답례품호두강정,기본,70.0,4.0,0,0,0.00,0,0
21,결혼답례품호두정과,기본,70.0,4.0,0,0,0.00,0,0
22,결혼식답례품호두강정,기본,70.0,4.0,1,0,0.00,0,0
23,답례품호두,기본,70.0,4.0,0,0,0.00,0,0
24,답례품호두강정,기본,70.0,4.0,1,0,0.00,0,0
25,답례품호두정과,기본,70.0,4.0,0,0,0.00,0,0
26,답례호두강정,기본,70.0,4.0,0,0,0.00,0,0
27,답례호두정과,기본,70.0,4.0,0,0,0.00,0,0
28,호두강정선물,기본,70.0,4.0,0,0,0.00,0,0
29,호두강정선물세트,기본,70.0,4.0,0,0,0.00,0,0
30,호두답례품,기본,70.0,4.0,0,0,0.00,0,0
31,호두정과답례,기본,70.0,4.0,0,0,0.00,0,0
32,호두정과선물,기본,70.0,4.0,0,0,0.00,0,0
33,호두정과선물세트,기본,70.0,4.0,0,0,0.00,0,0

In [53]:
group1 = list3.groupby(['키워드'])['노출수','클릭수'].sum().sort_values(by = '노출수', ascending=False)

/var/folders/j6/txnqzgpx1wx4nmdw439z1jn80000gn/T/ipykernel_3386/3231069820.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  group1 = list3.groupby(['키워드'])['노출수','클릭수'].sum().sort_values(by = '노출수', ascending=False)

In [54]:

group1['클릭률'] = group1['클릭수']/group1['노출수'] *100

In [59]:
group1['클릭률'] = group1['클릭률'].fillna(0)

In [63]:
TOP3 = group1[:3]
TOP3

          노출수  클릭수       클릭률
키워드
호두정과답례품  5068   25  0.493291
호두강정     4031   19  0.471347
호두강정답례품   696    2  0.287356

In [69]:
print(TOP3.index)

Index(['호두정과답례품', '호두강정', '호두강정답례품'], dtype='object', name='키워드')

In [103]:
df1 = pd.read_excel('로아스.xlsx')
df1.head(1)

,채널속성,채널그룹,채널명,채널상세,고객수,유입수,광고비,페이지수,유입당 페이지수,결제수(마지막클릭),유입당 결제율(마지막클릭),결제금액(마지막클릭),유입당 결제금액(마지막클릭),ROAS(마지막클릭),결제수(+14일기여도추정),유입당 결제율(+14일기여도추정),결제금액(+14일기여도추정),유입당 결제금액(+14일기여도추정),ROAS(+14일기여도추정)
0,모바일,검색광고,네이버 쇼핑검색광고,NaN,4457,5707,7663612,6699,1.173822,117,0.020501,25402000,4451.025057,3.314625,160.192919,0.02807,3.171165e+07,5556.623798,4.137951

In [83]:
df2 = df1.groupby(['채널명'])['광고비','결제금액(+14일기여도추정)'].sum()
df2['결제금액(+14일기여도추정)'] = round(df2['결제금액(+14일기여도추정)'])
df2['결제금액(+14일기여도추정)'] = df2['결제금액(+14일기여도추정)'].astype(int)

/var/folders/j6/txnqzgpx1wx4nmdw439z1jn80000gn/T/ipykernel_3386/3462292593.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df2 = df1.groupby(['채널명'])['광고비','결제금액(+14일기여도추정)'].sum()

In [90]:
df2['ROAS'] = df2['결제금액(+14일기여도추정)'] / df2.광고비 *100
df2['ROAS']= df2['ROAS'].replace([np.nan, np.inf, -np.inf], 0)
df2

                    광고비  결제금액(+14일기여도추정)        ROAS
채널명
구글검색                  0                0    0.000000
기타채널                  0                0    0.000000
네이버 모바일메인             0           995517    0.000000
네이버 블로그               0           900000    0.000000
네이버 사이트검색광고     1140348          5061244  443.833286
네이버 성과형디스플레이광고        0                0    0.000000
네이버 쇼핑검색광고      8715487         37061695  425.239519
네이버검색                 0          4357853    0.000000
네이버모바일메인-쇼핑           0                0    0.000000
네이버쇼핑-검색              0          1863240    0.000000
네이버쇼핑-서비스             0          4615451    0.000000
네이버쇼핑-통합검색            0          3321126    0.000000
네이버톡톡                 0          7979697    0.000000
네이버페이                 0                0    0.000000
사용자정의                 0            65796    0.000000
웹사이트                  0          3302910    0.000000
유튜브                   0                0    0.000000
인스타그램                 0             7241    0.000000

In [91]:
df2.to_csv('마케팅채널별_ROAS지표.csv')

In [92]:
df1

,채널속성,채널그룹,채널명,채널상세,고객수,유입수,광고비,페이지수,유입당 페이지수,결제수(마지막클릭),유입당 결제율(마지막클릭),결제금액(마지막클릭),유입당 결제금액(마지막클릭),ROAS(마지막클릭),결제수(+14일기여도추정),유입당 결제율(+14일기여도추정),결제금액(+14일기여도추정),유입당 결제금액(+14일기여도추정),ROAS(+14일기여도추정)
0,모바일,검색광고,네이버 쇼핑검색광고,NaN,4457,5707,7663612,6699,1.173822,117,0.020501,25402000,4451.025057,3.314625,160.192919,0.028070,3.171165e+07,5556.623798,4.137951
1,모바일,검색광고,네이버 사이트검색광고,NaN,1096,1268,974545,2842,2.241325,31,0.024448,2979400,2349.684543,3.057222,36.526205,0.028806,3.429539e+06,2704.683375,3.519118
2,PC,검색광고,네이버 쇼핑검색광고,NaN,678,756,1051875,977,1.292328,14,0.018519,3489000,4615.079365,3.316934,22.327963,0.029534,5.350043e+06,7076.776752,5.086197
3,모바일,검색,네이버검색,NaN,369,510,0,1585,3.107843,43,0.084314,3885300,7618.235294,0.000000,44.483958,0.087223,3.846317e+06,7541.797472,0.000000
4,모바일,쇼핑,네이버페이,결제내역,307,503,0,641,1.274354,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
5,모바일,쇼핑,네이버쇼핑-통합검색,NaN,379,431,0,692,1.605568,24,0.055684,2447300,5678.190255,0.000000,25.533918,0.059243,3.054292e+06,7086.524511,0.000000
6,모바일,쇼핑,네이버페이,장바구니,144,249,0,403,1.618474,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
7,모바일,웹사이트,웹사이트,NaN,140,241,0,779,3.232365,27,0.112033,3191300,13241.908714,0.000000,29.123744,0.120845,3.158574e+06,13106.115183,0.000000
8,PC,검색광고,네이버 사이트검색광고,NaN,222,238,165803,483,2.029412,10,0.042017,1297100,5450.000000,7.823140,13.246553,0.055658,1.631705e+06,6855.904151,9.841228
9,모바일,메신저,네이버톡톡,NaN,115,230,0,474,2.060870,34,0.147826,7271400,31614.782609,0.000000,38.047304,0.165423,7.928170e+06,34470.303627,0.000000
10,모바일,일반유입,네이버 모바일메인,NaN,148,207,0,419,2.024155,9,0.043478,1730400,8359.420290,0.000000,7.787182,0.037619,9.955168e+05,4809.259971,0.000000
11,모바일,쇼핑,네이버쇼핑-서비스,공통,127,193,0,376,1.948187,32,0.165803,5458200,28280.829016,0.000000,25.839081,0.133881,4.416491e+06,22883.372366,0.000000
12,모바일,쇼핑,네이버쇼핑-검색,NaN,172,179,0,389,2.173184,8,0.044693,1138100,6358.100559,0.000000,10.010823,0.055926,8.420870e+05,4704.396685,0.000000
13,모바일,쇼핑,네이버페이,일반,84,119,0,194,1.630252,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
14,PC,쇼핑,네이버쇼핑-통합검색,NaN,97,104,0,231,2.221154,4,0.038462,198800,1911.538462,0.000000,5.101631,0.049054,2.668336e+05,2565.707665,0.000000
15,모바일,쇼핑,네이버쇼핑-서비스,쇼핑MY,69,104,0,159,1.528846,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
16,PC,검색,네이버검색,NaN,70,85,0,431,5.070588,6,0.070588,235000,2764.705882,0.000000,5.903020,0.069447,5.115365e+05,6018.077042,0.000000
17,PC,웹사이트,웹사이트,NaN,58,69,0,140,2.028986,4,0.057971,148900,2157.971014,0.000000,3.919060,0.056798,1.443360e+05,2091.825596,0.000000
18,모바일,소셜,네이버 블로그,NaN,48,64,0,179,2.796875,5,0.078125,350000,5468.750000,0.000000,6.140632,0.095947,3.821100e+05,5970.468018,0.000000
19,모바일,광고,네이버 성과형디스플레이광고,NaN,40,59,0,68,1.152542,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
20,PC,쇼핑,네이버쇼핑-검색,NaN,54,57,0,87,1.526316,7,0.122807,778000,13649.122807,0.000000,8.641067,0.151598,1.021153e+06,17914.973429,0.000000
21,PC,쇼핑,네이버페이,결제내역,33,50,0,74,1.480000,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
22,PC,쇼핑,네이버페이,장바구니,31,49,0,96,1.959184,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
23,모바일,소셜,인스타그램,NaN,38,43,0,125,2.906977,0,0.000000,0,0.000000,0.000000,0.147766,0.003436,7.240527e+03,168.384340,0.000000
24,PC,소셜,네이버 블로그,NaN,19,30,0,74,2.466667,2,0.066667,499000,16633.333333,0.000000,2.370396,0.079013,5.178902e+05,17263.006055,0.000000
25,모바일,사용자정의,사용자정의,NaN,20,23,0,84,3.652174,2,0.086957,56000,2434.782609,0.000000,1.627886,0.070778,6.561080e+04,2852.643565,0.000000
26,PC,쇼핑,네이버페이,일반,11,14,0,41,2.928571,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
27,PC,쇼핑,네이버쇼핑-서비스,공통,11,13,0,13,1.000000,1,0.076923,293000,22538.461538,0.000000,0.679044,0.052234,1.989598e+05,15304.603365,0.000000
28,PC,광고,네이버 성과형디스플레이광고,NaN,10,12,0,17,1.416667,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
29,PC,메신저,네이버톡톡,NaN,8,10,0,24,2.400000,1,0.100000,21000,2100.000000,0.000000,2.339010,0.233901,5.152718e+04,5152.717969,0.000000
30,PC,쇼핑,네이버쇼핑-서비스,쇼핑MY,10,10,0,20,2.000000,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
31,모바일,소셜,유튜브,NaN,9,9,0,29,3.222222,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
32,PC,검색,구글검색,NaN,7,8,0,36,4.500000,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
33,PC,기타,기타채널,NaN,4,5,0,6,1.200000,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
34,PC,소셜,유튜브,NaN,4,5,0,9,1.800000,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
35,모바일,일반유입,네이버모바일메인-쇼핑,NaN,2,5,0,5,1.000000,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
36,PC,사용자정의,사용자정의,NaN,3,4,0,6,1.500000,0,0.000000,0,0.000000,0.000000,0.009236,0.002309,1.847130e+02,46.178238,0.000000
37,PC,소셜,인스타그램,NaN,2,2,0,6,3.000000,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000

# 마케팅 채널별 유입수 및 유입당 결제율

In [105]:
df3 = df1.groupby(['채널명'])['유입수','결제금액(+14일기여도추정)','결제수(+14일기여도추정)'].sum()
df3['결제금액(+14일기여도추정)'] = round(df3['결제금액(+14일기여도추정)'])
df3['결제금액(+14일기여도추정)'] = df3['결제금액(+14일기여도추정)'].astype(int)
df3.head(10)

/var/folders/j6/txnqzgpx1wx4nmdw439z1jn80000gn/T/ipykernel_3386/2982644882.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df3 = df1.groupby(['채널명'])['유입수','결제금액(+14일기여도추정)','결제수(+14일기여도추정)'].sum()

                 유입수  결제금액(+14일기여도추정)  결제수(+14일기여도추정)
채널명
구글검색               8                0        0.000000
기타채널               5                0        0.000000
네이버 모바일메인        207           995517        7.787182
네이버 블로그           94           900000        8.511028
네이버 사이트검색광고     1506          5061244       49.772757
네이버 성과형디스플레이광고    71                0        0.000000
네이버 쇼핑검색광고      6463         37061695      182.520882
네이버검색            595          4357853       50.386978
네이버모바일메인-쇼핑        5                0        0.000000
네이버쇼핑-검색         236          1863240       18.651890

In [111]:
df3['유입당_결제율'] = df3['결제수(+14일기여도추정)'] / df3['유입수'] *100
df3['유입당_결제금액'] = df3['결제금액(+14일기여도추정)']/df3['유입수']
df3

                 유입수  결제금액(+14일기여도추정)  결제수(+14일기여도추정)    유입당_결제율      유입당_결제금액
채널명
구글검색               8                0        0.000000   0.000000      0.000000
기타채널               5                0        0.000000   0.000000      0.000000
네이버 모바일메인        207           995517        7.787182   3.761923   4809.260870
네이버 블로그           94           900000        8.511028   9.054285   9574.468085
네이버 사이트검색광고     1506          5061244       49.772757   3.304964   3360.719788
네이버 성과형디스플레이광고    71                0        0.000000   0.000000      0.000000
네이버 쇼핑검색광고      6463         37061695      182.520882   2.824089   5734.441436
네이버검색            595          4357853       50.386978   8.468400   7324.122689
네이버모바일메인-쇼핑        5                0        0.000000   0.000000      0.000000
네이버쇼핑-검색         236          1863240       18.651890   7.903343   7895.084746
네이버쇼핑-서비스        320          4615451       26.518124   8.286914  14423.284375
네이버쇼핑-통합검색       535          3321126       30.635550   5.726271   6207.712150
네이버톡톡            240          7979697       40.386314  16.827631  33248.737500
네이버페이            984                0        0.000000   0.000000      0.000000
사용자정의             27            65796        1.637121   6.063412   2436.888889
웹사이트             310          3302910       33.042804  10.658969  10654.548387
유튜브               14                0        0.000000   0.000000      0.000000
인스타그램             45             7241        0.147766   0.328369    160.911111

In [112]:
df3.to_csv('마케팅채널별_유입.csv')

In [114]:
df4 = pd.read_excel('모든광고통계.xlsx')
df4

,캠페인 ID,상태,캠페인 이름,캠페인 유형,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)",하루예산,키워드수,전환수,전환율(%),광고수익률(%)
0,NaN,NaN,전체 결과,NaN,119323,379,0.32,1601,"606,837원",NaN,0,5,1.32,276.37
1,NaN,NaN,목록 외 캠페인 결과,NaN,1667,8,0.48,1734,"13,871원",NaN,0,1,12.50,302.79
2,NaN,NaN,캠페인 7개 결과,NaN,117656,371,0.32,1598,"592,966원",NaN,36,4,1.08,275.75
3,cmp-a001-02-000000008262454,노출가능,메인2)24.06.26 - 호두정과 170g,쇼핑검색,28503,52,0.19,1581,82192,"15,000원",0,0,0.00,0.00
4,cmp-a001-02-000000008262668,노출가능,서브)24.06.26 호두정과 실속형,쇼핑검색,1386,3,0.22,198,594,"50,000원",0,0,0.00,0.00
5,cmp-a001-02-000000008262441,노출가능,메인1)24.06.26 - 호두정과 80g,쇼핑검색,63448,174,0.28,2169,377443,"35,000원",0,4,2.30,433.20
6,cmp-a001-02-000000008262688,노출가능,서브)24.06.26 호두정과 답례품 4구,쇼핑검색,1821,5,0.28,172,858,"50,000원",0,0,0.00,0.00
7,cmp-a001-02-000000008262678,노출가능,서브)24.06.26 호두정과 답례품 3구,쇼핑검색,2227,13,0.59,169,2200,"50,000원",0,0,0.00,0.00
8,cmp-a001-01-000000008263001,노출가능,파워링크_24.06.26,파워링크,16854,101,0.60,986,99616,"10,000원",36,0,0.00,0.00
9,cmp-a001-02-000000008262512,노출가능,메인3) 24.06.26 - 호두정과 답례품2구,쇼핑검색,3417,23,0.68,1307,30063,"50,000원",0,0,0.00,0.00

In [115]:
df4 = df4.iloc[3:,:]
df4

,캠페인 ID,상태,캠페인 이름,캠페인 유형,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)",하루예산,키워드수,전환수,전환율(%),광고수익률(%)
3,cmp-a001-02-000000008262454,노출가능,메인2)24.06.26 - 호두정과 170g,쇼핑검색,28503,52,0.19,1581,82192,"15,000원",0,0,0.0,0.0
4,cmp-a001-02-000000008262668,노출가능,서브)24.06.26 호두정과 실속형,쇼핑검색,1386,3,0.22,198,594,"50,000원",0,0,0.0,0.0
5,cmp-a001-02-000000008262441,노출가능,메인1)24.06.26 - 호두정과 80g,쇼핑검색,63448,174,0.28,2169,377443,"35,000원",0,4,2.3,433.2
6,cmp-a001-02-000000008262688,노출가능,서브)24.06.26 호두정과 답례품 4구,쇼핑검색,1821,5,0.28,172,858,"50,000원",0,0,0.0,0.0
7,cmp-a001-02-000000008262678,노출가능,서브)24.06.26 호두정과 답례품 3구,쇼핑검색,2227,13,0.59,169,2200,"50,000원",0,0,0.0,0.0
8,cmp-a001-01-000000008263001,노출가능,파워링크_24.06.26,파워링크,16854,101,0.60,986,99616,"10,000원",36,0,0.0,0.0
9,cmp-a001-02-000000008262512,노출가능,메인3) 24.06.26 - 호두정과 답례품2구,쇼핑검색,3417,23,0.68,1307,30063,"50,000원",0,0,0.0,0.0

In [123]:
df4.loc[(df4['캠페인 유형']=='파워링크')|(df4['캠페인 이름']=='메인1)24.06.26 - 호두정과 80g')]

,캠페인 ID,상태,캠페인 이름,캠페인 유형,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)",하루예산,키워드수,전환수,전환율(%),광고수익률(%)
5,cmp-a001-02-000000008262441,노출가능,메인1)24.06.26 - 호두정과 80g,쇼핑검색,63448,174,0.28,2169,377443,"35,000원",0,4,2.3,433.2
8,cmp-a001-01-000000008263001,노출가능,파워링크_24.06.26,파워링크,16854,101,0.60,986,99616,"10,000원",36,0,0.0,0.0

In [124]:
df4.to_csv('파워링크_쇼핑검색_비교.csv')

### 키워드별 유입수 및 결제율

In [46]:
import pandas as pd
df5 = pd.read_excel('/Users/kang_hiee/Documents/GitHub/ubion/python/최종프로젝트/파워링크/키워드별_유입수및_결제율.xlsx')
df5.head(2)

/Users/kang_hiee/miniforge3/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,채널속성,채널그룹,채널명,키워드,고객수,유입수,페이지수,유입당 페이지수,결제수(마지막클릭),유입당 결제율(마지막클릭),결제금액(마지막클릭),유입당 결제금액(마지막클릭),결제수(+14일기여도추정),유입당 결제율(+14일기여도추정),결제금액(+14일기여도추정),유입당 결제금액(+14일기여도추정)
0,모바일,검색광고,네이버 쇼핑검색광고,호두강정,1609,1964,2318,1.180244,36,0.018330,5303700,2700.458248,46.137924,0.023492,6.192659e+06,3153.085151
1,모바일,검색광고,네이버 쇼핑검색광고,호두정과답례품,1048,1369,1547,1.130022,33,0.024105,7448700,5440.978817,43.972105,0.032120,8.625262e+06,6300.410704

In [47]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456 entries, 0 to 455
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   채널속성                 456 non-null    object
 1   채널그룹                 456 non-null    object
 2   채널명                  456 non-null    object
 3   키워드                  456 non-null    object
 4   고객수                  456 non-null    int64
 5   유입수                  456 non-null    int64
 6   페이지수                 456 non-null    int64
 7   유입당 페이지수             456 non-null    float64
 8   결제수(마지막클릭)           456 non-null    int64
 9   유입당 결제율(마지막클릭)       456 non-null    float64
 10  결제금액(마지막클릭)          456 non-null    int64
 11  유입당 결제금액(마지막클릭)      456 non-null    float64
 12  결제수(+14일기여도추정)       456 non-null    float64
 13  유입당 결제율(+14일기여도추정)   456 non-null    float64
 14  결제금액(+14일기여도추정)      456 non-null    float64
 15  유입당 결제금액(+14일기여도추정)  456 non-null    float64
dtypes: float64(7), int64(5), object(4)
memory usage: 57.1+ KB

In [48]:
df5.채널명.unique()

array(['네이버 쇼핑검색광고', '네이버 사이트검색광고', '네이버검색', '네이버쇼핑-통합검색', '네이버쇼핑-검색',
       '구글검색'], dtype=object)

In [49]:
keyword_df = df5.sort_values('유입수', ascending=False)[:50]['키워드']

In [50]:
keyword_df = keyword_df.drop_duplicates(keep='first')
keyword_df = keyword_df[keyword_df!='(검색어 없음)']
keyword_df

0          호두강정
1       호두정과답례품
2       호두강정답례품
3          호두정과
8       답례품호두강정
9            후백
11        hu100
17       호두정과답례
24      답례품호두정과
29        답례품호두
31       후백호두강정
32        호두답례품
34        답례품정과
35    hu100호두강정
36        답례품강정
38           정과
41        결혼답례품
45         강정세트
47      hu100호두
48        견과류정과
Name: 키워드, dtype: object

In [51]:
# 후백, hu100을 치고 유입된 고객은 지인분으로 추정하여 제외
keyword_df = keyword_df[(keyword_df!='hu100호두강정')&(keyword_df!='hu100호두')&(keyword_df!='hu100')&(keyword_df!='후백')&(keyword_df!='후백호두강정')]
# 현재 이미 사용중인 키워드 제외

In [70]:
list1 = pd.read_excel('./파워링크1.xlsx')
list1 = list1.drop(index=0)
list2 = pd.read_excel('./파워링크2.xlsx')
list2 = list2.drop(index=0)
list3 = pd.concat([list1, list2], axis=0)
list3 = list3.iloc[:,2:]
list3.reset_index(drop=True,inplace = True)

In [71]:
list3

,키워드,입찰가 유형,입찰가,품질지수,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
0,호두정과,키워드,1000.0,5.0,1054,5,0.48,999,4994
1,호두강정,키워드,1000.0,4.0,291,3,1.04,1093,3278
2,호두정과답례품,키워드,1000.0,5.0,669,2,0.30,671,1342
3,결혼답례품견과류,기본,70.0,4.0,0,0,0.00,0,0
4,결혼답례품호두강정,기본,70.0,4.0,0,0,0.00,0,0
5,결혼답례품호두정과,기본,70.0,4.0,0,0,0.00,0,0
6,결혼식답례품호두강정,기본,70.0,4.0,0,0,0.00,0,0
7,답례품호두강정,기본,70.0,4.0,1,0,0.00,0,0
8,답례품호두정과,기본,70.0,4.0,0,0,0.00,0,0
9,답례호두강정,기본,70.0,4.0,0,0,0.00,0,0
10,답례호두정과,기본,70.0,4.0,0,0,0.00,0,0
11,호두강정답례품,키워드,1000.0,4.0,207,0,0.00,0,0
12,호두강정선물세트,기본,70.0,4.0,1,0,0.00,0,0
13,호두답례품,기본,70.0,4.0,1,0,0.00,0,0
14,호두정과답례,기본,70.0,4.0,1,0,0.00,0,0
15,호두정과선물,기본,70.0,4.0,1,0,0.00,0,0
16,호두정과선물세트,기본,70.0,4.0,1,0,0.00,0,0
17,호두정과,키워드,1000.0,5.0,5997,50,0.84,967,48334
18,호두정과답례품,키워드,1000.0,5.0,4399,23,0.53,1052,24189
19,호두강정,키워드,1000.0,4.0,3740,16,0.43,996,15939
20,호두강정답례품,키워드,1000.0,4.0,489,2,0.41,770,1540
21,결혼답례품견과류,기본,70.0,4.0,0,0,0.00,0,0
22,결혼답례품호두강정,기본,70.0,4.0,0,0,0.00,0,0
23,결혼답례품호두정과,기본,70.0,4.0,0,0,0.00,0,0
24,결혼식답례품호두강정,기본,70.0,4.0,1,0,0.00,0,0
25,답례품호두,기본,70.0,4.0,0,0,0.00,0,0
26,답례품호두강정,기본,70.0,4.0,1,0,0.00,0,0
27,답례품호두정과,기본,70.0,4.0,0,0,0.00,0,0
28,답례호두강정,기본,70.0,4.0,0,0,0.00,0,0
29,답례호두정과,기본,70.0,4.0,0,0,0.00,0,0
30,호두강정선물,기본,70.0,4.0,0,0,0.00,0,0
31,호두강정선물세트,기본,70.0,4.0,0,0,0.00,0,0
32,호두답례품,기본,70.0,4.0,0,0,0.00,0,0
33,호두정과답례,기본,70.0,4.0,0,0,0.00,0,0
34,호두정과선물,기본,70.0,4.0,0,0,0.00,0,0
35,호두정과선물세트,기본,70.0,4.0,0,0,0.00,0,0

In [72]:
current_powerlink = list3['키워드'].drop_duplicates(keep='first')
current_powerlink

0           호두정과
1           호두강정
2        호두정과답례품
3       결혼답례품견과류
4      결혼답례품호두강정
5      결혼답례품호두정과
6     결혼식답례품호두강정
7        답례품호두강정
8        답례품호두정과
9         답례호두강정
10        답례호두정과
11       호두강정답례품
12      호두강정선물세트
13         호두답례품
14        호두정과답례
15        호두정과선물
16      호두정과선물세트
25         답례품호두
30        호두강정선물
Name: 키워드, dtype: object

In [73]:
# current_powerlink에 없는 키워드만 선택
filtered_keyword_df = keyword_df[~keyword_df.isin(current_powerlink)]

In [74]:
# 이 키워드를 통한 유입 이력이 있으니 이 키워드를 파워링크에 대입 해보자!!!
filtered_keyword_df

34    답례품정과
36    답례품강정
38       정과
41    결혼답례품
45     강정세트
48    견과류정과
Name: 키워드, dtype: object